# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26e2982b0e2da3618593fcaef4dee6381bc16c76d961f8ef3b4fc581c410588b6e919746bfb35329997d1ebc4a417d92e32483f153cbaccdeb1669292361082

test:
  secret_key_base: 290b8cf0ffd56132505ffd941e39ebed1ba8042f40538c82775ba3061ec0a1fcf4c6d45bb3d0c01e06894ad44c7b1bd21b1a0b4f169ba2a00be5aff5eed6f19e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
